- hosts: webserver
  user: root
  connection: ssh
  become: yes
  tasks:
  - name: Executing webserver role using cron
    cron: name="Executing webserver role using cron" minute="10" hour="5" job="ansible-playbook webserver.yml > root/cron.log"
