- hosts: all
  connection: ssh
  user: root
  become: yes
  gather_facts: yes
  vars: 
    username: root
    userpassword: india@123
    connectiontype: sftp
  tasks: 
    - name: Install the configuration file customized for the system
      template: src=/root/playbooks/mytemplates/test.conf.j2 dest=/root/test1.conf owner=root mode=750
