--- #Adding users using loop

- hosts: all
  user: root
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Add list of users
    user: name={{ item }} state=present group=wheel
    with_items:
      - dhoni
      - virat
      - Raj
      - Rao
      - Madhavan
      - Kalyan
  - name: Remove user from the list
    user: name={{ item }} state=absent
    with_items:
     - virat
     - Raj


   
