- hosts: local webserver
  user: root
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Run the uptime command on all hosts and log it
      raw: /usr/bin/uptime >> /root/uptime.log
      run_once: true
      #ignore_errors: yes
